### ISSUE TITLE
lat/lng coordinates from mapbox output to Reps

### ISSUE THREAD

**Issue by derekmiranda** [sunrisemvmtnyc/legislation-tracker#38]

**Comment by derekmiranda** [comment]
@twblackwell was this handled w/ [this PR](https://github.com/sunrisemvmtnyc/legislation-tracker/pull/37)? or is there still more work to do?

**Comment by twblackwell** [comment]
> @twblackwell was this handled w/ [this PR](https://github.com/sunrisemvmtnyc/legislation-tracker/pull/37)? or is there still more work to do?

That PR was one of two parts to this feature. I need to now take the lat/long coordinates and fetch the Reps for that location

**Comment by twblackwell** [comment]
The lat long coordinates are already fetched from mapbox. Then the coordinates are used in the OpenStates API to fetch the representative for that exact location (sometimes zip codes have multiple representative options - this avoids that).

Once the rep data is returned, their office location (city) and clickable phone number will display. In a later PR, I will improve the styling to match UI themes

**Comment by twblackwell** [comment]
Got the representatives data in a PR I'll link in a moment! Now I need to parse it as an array of json Objects and allow for clicking from the Bill page.

Next PR will be additional HTML rearranging and styling of the Bill page to better match the Figma.
