### ISSUE TITLE
Finalize UI

### ISSUE THREAD

**Issue by agreffard** [sunrisemvmtnyc/legislation-tracker#44]
Finalize/enhance global UI of the app: colors, fonts, responsiveness, etc

**Comment by elliott-king** [comment]
Notes from 5/15, possible considerations:
- use sunrise color palette
- hit up Nicole for design (?)

**Comment by derekmiranda** [comment]
here are some of sunrise's creative resources, should help with aligning design of our site: https://sites.google.com/sunrisemovement.org/hrd/creative?authuser=0

**Comment by derekmiranda** [comment]
sunrise colors (SCSS): https://drive.google.com/file/d/1zN8eBmbT2Zt74WuRFwinluqO0fSbX_g-/view?usp=drive_link

**Comment by elliott-king** [comment]
Linking updated design: 
https://www.figma.com/design/9iFKBdvUweHd2PKz1XviTc/Sunrise-Legislative-Tracker-Design?node-id=962-538&node-type=CANVAS&t=GvnU58Jda5bwjjtD-0

**Comment by elliott-king** [comment]
Closing - refer to Figma. Will open new tickets for each page (for the code).
